// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

sealed trait ExecutorState extends _root_.scalapb.GeneratedEnum {
  type EnumType = ExecutorState
  def isNew: _root_.scala.Boolean = false
  def isRegistered: _root_.scala.Boolean = false
  def isRunningJob: _root_.scala.Boolean = false
  def isIdle: _root_.scala.Boolean = false
  def isUnregistered: _root_.scala.Boolean = false
  def isAssumedDead: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ExecutorState] = com.jalebi.proto.jobmanagement.ExecutorState
}

object ExecutorState extends _root_.scalapb.GeneratedEnumCompanion[ExecutorState] {
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ExecutorState] = this
  @SerialVersionUID(0L)
  case object NEW extends ExecutorState {
    val value = 0
    val index = 0
    val name = "NEW"
    override def isNew: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object REGISTERED extends ExecutorState {
    val value = 1
    val index = 1
    val name = "REGISTERED"
    override def isRegistered: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RUNNING_JOB extends ExecutorState {
    val value = 2
    val index = 2
    val name = "RUNNING_JOB"
    override def isRunningJob: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDLE extends ExecutorState {
    val value = 3
    val index = 3
    val name = "IDLE"
    override def isIdle: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object UNREGISTERED extends ExecutorState {
    val value = 4
    val index = 4
    val name = "UNREGISTERED"
    override def isUnregistered: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ASSUMED_DEAD extends ExecutorState {
    val value = 5
    val index = 5
    val name = "ASSUMED_DEAD"
    override def isAssumedDead: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(value: _root_.scala.Int) extends ExecutorState with _root_.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(NEW, REGISTERED, RUNNING_JOB, IDLE, UNREGISTERED, ASSUMED_DEAD)
  def fromValue(value: _root_.scala.Int): ExecutorState = value match {
    case 0 => NEW
    case 1 => REGISTERED
    case 2 => RUNNING_JOB
    case 3 => IDLE
    case 4 => UNREGISTERED
    case 5 => ASSUMED_DEAD
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = JobmanagementProto.javaDescriptor.getEnumTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = JobmanagementProto.scalaDescriptor.enums(0)
}