// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

object JobmanagementProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.jalebi.proto.jobmanagement.RegisterExecutorRequest,
    com.jalebi.proto.jobmanagement.RegisterExecutorResponse,
    com.jalebi.proto.jobmanagement.HeartbeatRequest,
    com.jalebi.proto.jobmanagement.HeartbeatResponse,
    com.jalebi.proto.jobmanagement.TaskRequest,
    com.jalebi.proto.jobmanagement.TaskResponse
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CiZzcmMvbWFpbi9yZXNvdXJjZXMvam9ibWFuYWdlbWVudC5wcm90bxIQY29tLmphbGViaS5wcm90byI5ChdSZWdpc3RlckV4Z
  WN1dG9yUmVxdWVzdBIeCgpleGVjdXRvcklkGAEgASgJUgpleGVjdXRvcklkIkgKGFJlZ2lzdGVyRXhlY3V0b3JSZXNwb25zZRIsC
  hFoZWFydGJlYXRJbnRlcnZhbBgBIAEoA1IRaGVhcnRiZWF0SW50ZXJ2YWwiaQoQSGVhcnRiZWF0UmVxdWVzdBIeCgpleGVjdXRvc
  klkGAEgASgJUgpleGVjdXRvcklkEjUKBXN0YXRlGAIgASgOMh8uY29tLmphbGViaS5wcm90by5FeGVjdXRvclN0YXRlUgVzdGF0Z
  SIzChFIZWFydGJlYXRSZXNwb25zZRIeCgpleGVjdXRvcklkGAEgASgJUgpleGVjdXRvcklkIlQKC1Rhc2tSZXF1ZXN0EhQKBWpvY
  klEGAEgASgJUgVqb2JJRBIvCgJvcBgCIAEoDjIfLmNvbS5qYWxlYmkucHJvdG8uVGFza09wZXJhdGlvblICb3AiJAoMVGFza1Jlc
  3BvbnNlEhQKBWVwb2NoGAEgASgDUgVlcG9jaCpnCg1FeGVjdXRvclN0YXRlEgcKA05FVxAAEg4KClJFR0lTVEVSRUQQARIPCgtSV
  U5OSU5HX0pPQhACEggKBElETEUQAxIQCgxVTlJFR0lTVEVSRUQQBBIQCgxBU1NVTUVEX0RFQUQQBSpGCg1UYXNrT3BlcmF0aW9uE
  g4KClNUQVJUX1RBU0sQABINCglTVE9QX1RBU0sQARIWChJDT01QVVRFX05FWFRfQkFUQ0gQAiolCgRUYXNrEg4KCk1PUkVfVE9fR
  E8QABINCglJX0FNX0RPTkUQATKuAgoVSm9iTWFuYWdlbWVudFByb3RvY29sEmsKEHJlZ2lzdGVyRXhlY3V0b3ISKS5jb20uamFsZ
  WJpLnByb3RvLlJlZ2lzdGVyRXhlY3V0b3JSZXF1ZXN0GiouY29tLmphbGViaS5wcm90by5SZWdpc3RlckV4ZWN1dG9yUmVzcG9uc
  2UiABJWCgloZWFydGJlYXQSIi5jb20uamFsZWJpLnByb3RvLkhlYXJ0YmVhdFJlcXVlc3QaIy5jb20uamFsZWJpLnByb3RvLkhlY
  XJ0YmVhdFJlc3BvbnNlIgASUAoJc3RhcnRUYWxrEh0uY29tLmphbGViaS5wcm90by5UYXNrUmVxdWVzdBoeLmNvbS5qYWxlYmkuc
  HJvdG8uVGFza1Jlc3BvbnNlIgAoATABYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}