// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

object JobmanagementProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.jalebi.proto.jobmanagement.ExecutorRequest,
    com.jalebi.proto.jobmanagement.ExecutorResponse,
    com.jalebi.proto.jobmanagement.TaskRequest,
    com.jalebi.proto.jobmanagement.TaskResponse,
    com.jalebi.proto.jobmanagement.VertexResult,
    com.jalebi.proto.jobmanagement.EdgeResult,
    com.jalebi.proto.jobmanagement.HostPort
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CiZzcmMvbWFpbi9yZXNvdXJjZXMvam9ibWFuYWdlbWVudC5wcm90bxIQY29tLmphbGViaS5wcm90byIxCg9FeGVjdXRvclJlc
  XVlc3QSHgoKZXhlY3V0b3JJZBgBIAEoCVIKZXhlY3V0b3JJZCJ4ChBFeGVjdXRvclJlc3BvbnNlEiwKEWhlYXJ0YmVhdEludGVyd
  mFsGAEgASgDUhFoZWFydGJlYXRJbnRlcnZhbBI2Cghob3N0cG9ydBgCIAEoCzIaLmNvbS5qYWxlYmkucHJvdG8uSG9zdFBvcnRSC
  Ghvc3Rwb3J0IscBCgtUYXNrUmVxdWVzdBIUCgVqb2JJZBgBIAEoCVIFam9iSWQSNgoIdGFza1R5cGUYAiABKA4yGi5jb20uamFsZ
  WJpLnByb3RvLlRhc2tUeXBlUgh0YXNrVHlwZRIkCg1zdGFydFZlcnRleElkGAMgASgDUg1zdGFydFZlcnRleElkEhgKB2RhdGFzZ
  XQYBCABKAlSB2RhdGFzZXQSFAoFcGFydHMYBSADKAlSBXBhcnRzEhQKBWxpbWl0GAYgASgDUgVsaW1pdCLVAgoMVGFza1Jlc3Bvb
  nNlEhQKBWpvYklkGAEgASgJUgVqb2JJZBIeCgpleGVjdXRvcklkGAIgASgJUgpleGVjdXRvcklkEkUKDWV4ZWN1dG9yU3RhdGUYA
  yABKA4yHy5jb20uamFsZWJpLnByb3RvLkV4ZWN1dG9yU3RhdGVSDWV4ZWN1dG9yU3RhdGUSQgoMZGF0YXNldFN0YXRlGAQgASgOM
  h4uY29tLmphbGViaS5wcm90by5EYXRhc2V0U3RhdGVSDGRhdGFzZXRTdGF0ZRJECg12ZXJ0ZXhSZXN1bHRzGAUgAygLMh4uY29tL
  mphbGViaS5wcm90by5WZXJ0ZXhSZXN1bHRSDXZlcnRleFJlc3VsdHMSPgoLZWRnZVJlc3VsdHMYBiADKAsyHC5jb20uamFsZWJpL
  nByb3RvLkVkZ2VSZXN1bHRSC2VkZ2VSZXN1bHRzIqEBCgxWZXJ0ZXhSZXN1bHQSGgoIdmVydGV4SWQYASABKANSCHZlcnRleElkE
  jwKBGRhdGEYAiADKAsyKC5jb20uamFsZWJpLnByb3RvLlZlcnRleFJlc3VsdC5EYXRhRW50cnlSBGRhdGEaNwoJRGF0YUVudHJ5E
  hAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgJUgV2YWx1ZToCOAEi0QEKCkVkZ2VSZXN1bHQSJgoOc291cmNlVmVydGV4S
  WQYASABKANSDnNvdXJjZVZlcnRleElkEiYKDnRhcmdldFZlcnRleElkGAIgASgDUg50YXJnZXRWZXJ0ZXhJZBI6CgRkYXRhGAMgA
  ygLMiYuY29tLmphbGViaS5wcm90by5FZGdlUmVzdWx0LkRhdGFFbnRyeVIEZGF0YRo3CglEYXRhRW50cnkSEAoDa2V5GAEgASgJU
  gNrZXkSFAoFdmFsdWUYAiABKAlSBXZhbHVlOgI4ASJKCghIb3N0UG9ydBIWCgZzY2hlbWUYASABKAlSBnNjaGVtZRISCgRob3N0G
  AIgASgJUgRob3N0EhIKBHBvcnQYAyABKANSBHBvcnQqawoNRXhlY3V0b3JTdGF0ZRIHCgNORVcQABIOCgpSRUdJU1RFUkVEEAESD
  woLUlVOTklOR19KT0IQBBIMCghSVU5OQUJMRRAFEhAKDFVOUkVHSVNURVJFRBAGEhAKDEFTU1VNRURfREVBRBAHKjEKDERhdGFzZ
  XRTdGF0ZRIICgROT05FEAASCwoHTE9BRElORxABEgoKBkxPQURFRBACKlMKCFRhc2tUeXBlEhAKDExPQURfREFUQVNFVBAAEhEKD
  VNFQVJDSF9WRVJURVgQARIRCg1CUkVBRFRIX0ZJUlNUEAISDwoLREVQVEhfRklSU1QQAzKlAgoVSm9iTWFuYWdlbWVudFByb3RvY
  29sElsKEHJlZ2lzdGVyRXhlY3V0b3ISIS5jb20uamFsZWJpLnByb3RvLkV4ZWN1dG9yUmVxdWVzdBoiLmNvbS5qYWxlYmkucHJvd
  G8uRXhlY3V0b3JSZXNwb25zZSIAEl0KEnVucmVnaXN0ZXJFeGVjdXRvchIhLmNvbS5qYWxlYmkucHJvdG8uRXhlY3V0b3JSZXF1Z
  XN0GiIuY29tLmphbGViaS5wcm90by5FeGVjdXRvclJlc3BvbnNlIgASUAoJc3RhcnRUYWxrEh4uY29tLmphbGViaS5wcm90by5UY
  XNrUmVzcG9uc2UaHS5jb20uamFsZWJpLnByb3RvLlRhc2tSZXF1ZXN0IgAoATABYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}