// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

object JobmanagementProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.jalebi.proto.jobmanagement.ExecutorRequest,
    com.jalebi.proto.jobmanagement.ExecutorResponse,
    com.jalebi.proto.jobmanagement.HeartbeatRequest,
    com.jalebi.proto.jobmanagement.HeartbeatResponse,
    com.jalebi.proto.jobmanagement.TaskRequest,
    com.jalebi.proto.jobmanagement.TaskResponse
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CiZzcmMvbWFpbi9yZXNvdXJjZXMvam9ibWFuYWdlbWVudC5wcm90bxIQY29tLmphbGViaS5wcm90byIxCg9FeGVjdXRvclJlc
  XVlc3QSHgoKZXhlY3V0b3JJZBgBIAEoCVIKZXhlY3V0b3JJZCJAChBFeGVjdXRvclJlc3BvbnNlEiwKEWhlYXJ0YmVhdEludGVyd
  mFsGAEgASgDUhFoZWFydGJlYXRJbnRlcnZhbCJpChBIZWFydGJlYXRSZXF1ZXN0Eh4KCmV4ZWN1dG9ySWQYASABKAlSCmV4ZWN1d
  G9ySWQSNQoFc3RhdGUYAiABKA4yHy5jb20uamFsZWJpLnByb3RvLkV4ZWN1dG9yU3RhdGVSBXN0YXRlIjMKEUhlYXJ0YmVhdFJlc
  3BvbnNlEh4KCmV4ZWN1dG9ySWQYASABKAlSCmV4ZWN1dG9ySWQiVAoLVGFza1JlcXVlc3QSFAoFam9iSUQYASABKAlSBWpvYklEE
  i8KAm9wGAIgASgOMh8uY29tLmphbGViaS5wcm90by5UYXNrT3BlcmF0aW9uUgJvcCIkCgxUYXNrUmVzcG9uc2USFAoFZXBvY2gYA
  SABKANSBWVwb2NoKmcKDUV4ZWN1dG9yU3RhdGUSBwoDTkVXEAASDgoKUkVHSVNURVJFRBABEg8KC1JVTk5JTkdfSk9CEAISCAoES
  URMRRADEhAKDFVOUkVHSVNURVJFRBAEEhAKDEFTU1VNRURfREVBRBAFKkYKDVRhc2tPcGVyYXRpb24SDgoKU1RBUlRfVEFTSxAAE
  g0KCVNUT1BfVEFTSxABEhYKEkNPTVBVVEVfTkVYVF9CQVRDSBACKiUKBFRhc2sSDgoKTU9SRV9UT19ETxAAEg0KCUlfQU1fRE9OR
  RABMv0CChVKb2JNYW5hZ2VtZW50UHJvdG9jb2wSWwoQcmVnaXN0ZXJFeGVjdXRvchIhLmNvbS5qYWxlYmkucHJvdG8uRXhlY3V0b
  3JSZXF1ZXN0GiIuY29tLmphbGViaS5wcm90by5FeGVjdXRvclJlc3BvbnNlIgASXQoSdW5yZWdpc3RlckV4ZWN1dG9yEiEuY29tL
  mphbGViaS5wcm90by5FeGVjdXRvclJlcXVlc3QaIi5jb20uamFsZWJpLnByb3RvLkV4ZWN1dG9yUmVzcG9uc2UiABJWCgloZWFyd
  GJlYXQSIi5jb20uamFsZWJpLnByb3RvLkhlYXJ0YmVhdFJlcXVlc3QaIy5jb20uamFsZWJpLnByb3RvLkhlYXJ0YmVhdFJlc3Bvb
  nNlIgASUAoJc3RhcnRUYWxrEh0uY29tLmphbGViaS5wcm90by5UYXNrUmVxdWVzdBoeLmNvbS5qYWxlYmkucHJvdG8uVGFza1Jlc
  3BvbnNlIgAoATABYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}