// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

sealed trait Task extends _root_.scalapb.GeneratedEnum {
  type EnumType = Task
  def isMoreToDo: _root_.scala.Boolean = false
  def isIAmDone: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[Task] = com.jalebi.proto.jobmanagement.Task
}

object Task extends _root_.scalapb.GeneratedEnumCompanion[Task] {
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Task] = this
  @SerialVersionUID(0L)
  case object MORE_TO_DO extends Task {
    val value = 0
    val index = 0
    val name = "MORE_TO_DO"
    override def isMoreToDo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object I_AM_DONE extends Task {
    val value = 1
    val index = 1
    val name = "I_AM_DONE"
    override def isIAmDone: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(value: _root_.scala.Int) extends Task with _root_.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(MORE_TO_DO, I_AM_DONE)
  def fromValue(value: _root_.scala.Int): Task = value match {
    case 0 => MORE_TO_DO
    case 1 => I_AM_DONE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = JobmanagementProto.javaDescriptor.getEnumTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = JobmanagementProto.scalaDescriptor.enums(1)
}