// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jalebi.proto.jobmanagement

sealed trait TaskState extends _root_.scalapb.GeneratedEnum {
  type EnumType = TaskState
  def isRunning: _root_.scala.Boolean = false
  def isCompleted: _root_.scala.Boolean = false
  def isFailed: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[TaskState] = com.jalebi.proto.jobmanagement.TaskState
}

object TaskState extends _root_.scalapb.GeneratedEnumCompanion[TaskState] {
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[TaskState] = this
  @SerialVersionUID(0L)
  case object RUNNING extends TaskState {
    val value = 0
    val index = 0
    val name = "RUNNING"
    override def isRunning: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object COMPLETED extends TaskState {
    val value = 1
    val index = 1
    val name = "COMPLETED"
    override def isCompleted: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FAILED extends TaskState {
    val value = 2
    val index = 2
    val name = "FAILED"
    override def isFailed: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(value: _root_.scala.Int) extends TaskState with _root_.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(RUNNING, COMPLETED, FAILED)
  def fromValue(value: _root_.scala.Int): TaskState = value match {
    case 0 => RUNNING
    case 1 => COMPLETED
    case 2 => FAILED
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = JobmanagementProto.javaDescriptor.getEnumTypes.get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = JobmanagementProto.scalaDescriptor.enums(2)
}